### PR TITLE
2 feature navcard navcardlist

### PR DESCRIPTION
**Pull request by KatKozlowska**
Created NavCard and NavCardList. 
NavCardList renders the NavCard on the home page. 
Each Card will link to a page. 
Attempted implementation of dark mode, however unsure how it will be implemented yet. 
As discussed with project managers, the components are not reusable for the time being.

### CODE REVIEW

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you remove the nav card list from home after testing.
Can you add in the dark mode feature using the same conventions used for the header component

**Review by Chelsealily — APPROVED** [review]

**Comment by jm-go** [comment]
- Changes in Home have been removed
- Dark mode for NavCard has been added

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Remove commented out styles in navcard.scss

**Comment by jm-go** [comment]
Comment removed

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you add a prop in NavCardList so we can chose we chose which mode, light/dark, nav cards are displayed in

**Comment by KatKozlowska** [comment]
- Added variant in NavCardList.
- Renamed folders for types after component.

**Review by Matthew-Hughes3488 — APPROVED** [review]
Great code :)

**Pull request merged**
