### PR TITLE
14 feature staffnavcard staffnavlist

### PR DESCRIPTION
**Pull request by KatKozlowska**
- Added StaffNavCard and StaffNavList including styling. 
- Added temporary data file with types and list. 
- Desktop version to be updated when drop down is added to the header component.

### CODE REVIEW

**Review by Chelsealily — CHANGES_REQUESTED** [review]
Can you add light/dark mode styling options please as per the "Home" page on figma. Then all good :)

**Comment by jm-go** [comment]
Dark mode added.

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you add a prop in StaffCardList so we can chose we chose which mode, light/dark, staff cards are displayed in

**Comment by KatKozlowska** [comment]
- Added variant in StaffNavList

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you pull the updates from main so you have access to the new data folder, then add the new types you've made to it

**Comment by KatKozlowska** [comment]
- Changed folder structure to follow correct conventions (On both NavCard and StaffNav )

**Review by Matthew-Hughes3488 — APPROVED** [review]
Great job. thanks for reorganising the data :)

**Review by Chelsealily — APPROVED** [review]
Great job girls :)

**Pull request merged**
