### PR TITLE
5 feature header component

### PR DESCRIPTION
**Pull request by mh-fung**
Added the header in Home and positioned the items, 
but the following message shows up in the command line when it's on the page so we guess the folder should be put in src file instead?
`Assets in public cannot be imported from JavaScript.
Instead of /public/images/logo.png, put the file in the src directory, and use /src/images/logo.png instead.`

### CODE REVIEW

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you update so the background colour is white when in desktop view.
Can you add a new prop to specify if we are loading the home component in dark or light mode when we use it.
Add a different background colour in the styles for dark mode to test that it works.

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Everything looks great :)
Can you add in the optional button component.

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you remove the header component from home after testing?
Can you make it so when I use the header component I can chose the label the goes in the button?
Can you make it so the button won't be visible is I pass buttonOption = false.

**Review by Matthew-Hughes3488 — APPROVED** [review]
Great code :)

**Review by Chelsealily — APPROVED** [review]

**Pull request merged**
