### PR TITLE
12 component client profile card

### PR DESCRIPTION
**Pull request by Chelsealily**
We created the ClientProfile component card compiling the client's contact and booking details eg. DOB, email address, mobile number etc. 

This can be found in Src > Components > ClientProfile

We also created a data type in Src > types  > ClientProfileTypes

Stylings - created light and dark versions as well as mobile and desktop versions. 

We have left two comments for hotfix's for the ProfilePicture component (on line 18 and 19 of the ClientProfile.tsx). Both of these props need to be made optional.

### CODE REVIEW

**Review by mh-fung — CHANGES_REQUESTED** [review]
Hi, 
Could you add the title for the client?
Please help to create the data for client as well in the data file.
Could you update the repo as well?
Thanks

**Comment by JMAdis** [comment]
added in requested changes & fixed some styling issues

**Review by mh-fung — CHANGES_REQUESTED** [review]
Nice and could you update the branch so that we can merge it into the main branch. Thanks

**Review by fihockey — CHANGES_REQUESTED** [review]
The profile picture source needs to be changed on the profile picture file, as this is running errors otherwise.

**Review by fihockey — APPROVED** [review]

**Review by mh-fung — APPROVED** [review]
Great. Thanks

**Pull request merged**
