### PR TITLE
11 feature staff profile card component

### PR DESCRIPTION
**Pull request by mh-fung**
Added staff profile card component
Added profile picture component, which could be used for both staff and client
Props are required to specify wether the role and the edit tag should be displayed

### CODE REVIEW

**Review by Chelsealily — CHANGES_REQUESTED** [review]
Hi please can you 
1. update repo to get the new data and types folder from main.
2. Add your types /data to that from now on
3. Add light and dark mode styles :)
Thanks!

**Review by Matthew-Hughes3488 — APPROVED** [review]
Great stuff :)

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Code is giving the following errors
src/components/ProfilePicture/ProfilePicture.tsx(17,3): error TS6133: 'variant' is declared but its value is never read.
src/components/StaffProfileCard/StaffProfileCard.tsx(10,36): error TS6133: 'variant' is declared but its value is never read.

**Comment by Chelsealily** [comment]
HI Hei and Nilum, in the Dark mode styles please can remove white border on bottom two boxes and change profile image background colour section to match the dark mode settings (dark background/white text)

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
There is still a white border in dark mode

**Review by Chelsealily — APPROVED** [review]
Great job :) !

**Review by Matthew-Hughes3488 — APPROVED** [review]
Great code :)

**Pull request merged**
