### PR TITLE
7 setup navigation

### PR DESCRIPTION
**Pull request by sachie5**
Created a NavBar component that has a list compiled of the icon, buttons and links to other pages on the website.

Accidentally created NavCard and NavCardList components for m=biel view accidentally so commented out code for future use.

### CODE REVIEW

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you add styles to the Nav bar.
Can you make it so the Nav bar is only displayed on desktop view.
Can you remove the nav card and nav card list components. Jo and Kat are working in it now

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Delete NavCard and NavCardList folder.
Add styles to match figma

**Comment by ghost** [comment]
Styles added.
NavCard and NavCard List components removed.

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Could you remove NavBar from the home page now that the testing is done.

**Review by Matthew-Hughes3488 — APPROVED** [review]
Looks great :)

**Review by Chelsealily — APPROVED** [review]

**Pull request merged**
