### PR TITLE
3 setup footer

### PR DESCRIPTION
**Pull request by ghost**
-Footer created and styled with link-HomeBtn.
-Css class created for dark mode footer.

### CODE REVIEW

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Looks great, just needs a prop so we can chose if we want to display it in dark mode or not.

**Review by Chelsealily — CHANGES_REQUESTED** [review]
Can you change the Light/Dark mode css to match the light and dark mode labels in the Header component please

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you change the media query to use the breakpoints in the global style files

**Review by Matthew-Hughes3488 — CHANGES_REQUESTED** [review]
Can you fix the styles on the home button to match figma.

**Review by Chelsealily — APPROVED** [review]
Looks good to me :) !

**Review by Matthew-Hughes3488 — APPROVED** [review]

**Pull request merged**
